#!/bin/bash
echo "Starting slice_integration..."
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,1,0 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 1,1,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 1,1,1 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,1,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 2,1,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 2,1,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 1,1,2 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 1,1,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 1,1,0 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 1,1,0 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,1,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 1,1,1 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 1,1,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 0,1,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 2,1,2 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 2,1,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 1,1,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 1,1,2 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 0,1,2 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 1,1,3 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 1,1,3 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 2,1,0 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 2,1,0 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,1,3 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 2,1,1 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 2,1,1 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,2,0 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 1,2,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 1,2,1 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 2,1,3 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 2,1,3 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,2,1 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 2,1,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 2,1,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par a --mode-ind 1,1,3 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 1,1,3 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 0,1,3 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par a --mode-ind 1,2,2 --nproc 8
python3 slice_integration.py --mode-fam TE --mode-par b --mode-ind 1,2,2 --nproc 8
python3 slice_integration.py --mode-fam TM --mode-par b --mode-ind 0,2,2 --nproc 8